### ISSUE TITLE
`tasks-json`, `version` and `help` flag should imply `silent`

### ISSUE THREAD

**Issue by demurgos** [gulpjs/gulp-cli#157]
The expected output of `tasks-json` is to emit a JSON representation of the available tasks to the standard output.
Some extra logs may be emitted, causing parse errors by consummers. For example when a gulpfile is transpiled, it emits the line `[<time>] Requiring external module <transpiler>` followed by the JSON output.

The workaround is to use the `--silent` flag to suppress the extra logs. Some tools may be missing this flag so they do not work reliably when extra logs are emitted.

Enabling the `--silent` flag automatically when `--tasks-json` is used and no log-level is configured would fix those errors and improve ergonomics.

- See [related Webstorm issue](https://youtrack.jetbrains.com/issue/WEB-28715)

**Comment by phated** [comment]
I thought we did this.  @sttk any ideas?  @demurgos which version of gulp - the --tasks-json recently was backported to 3.x and maybe we missed the silence part?

**Comment by sttk** [comment]
@demurgos @phated About `--tasks-json`, this issue can be fixed by adding `opts.tasksJson`  in [this condition](https://github.com/gulpjs/gulp-cli/blob/master/lib/shared/log/to-console.js#L35). I'll send a pr for this.

If it is needed to suppress requiring logs for `--version` and `--help` (and more flags?), a few more modifications are needed. (stop logging in first `toConsole`, and enable logging in second `toConsole`).

**Comment by demurgos** [comment]
`--version` and `--help` are intended for humans so the extra logs are less problemematic, but it still would be good to only keep the relevant information. The use of the transpiler is not related to the version or help. I did not look into the code details, but from a user point of view it may be surprising that these commands load the gulpfile.

**Comment by phated** [comment]
:shipit:

**Comment by phated** [comment]
A fix for this has been published in gulp-cli 2.1.0!
