### ISSUE TITLE
Clear "task did not complete" warning when an error occurs

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp-cli#162]
Ref https://github.com/gulpjs/gulp/issues/2168

**Comment by another-guy** [comment]
The false negatives (`Did you forget to signal async completion?`) reported by @MLoughry in the ref'ed issue is occurring to me to. I'm too talking specifically about the `gulp.parallel(failingTask, notFailingTask)` case.

Since the ref'ed issue has been closed, is this the right issue to subscribe for status notification(s)?
