### ISSUE TITLE
Request to update yargs dependency

### ISSUE THREAD

**Issue by pravi** [gulpjs/gulp-cli#194]
As per nodejs schedule https://nodejs.org/en/about/releases/ 8.x is lowest supported release. Do we still want to continue supporting node 0.10? yargs support node > 6. If it is okay to drop support for ancient node versions, I think we should update yargs.

**Comment by phated** [comment]
Hey @pravi, gulp 4 has committed to supporting node 0.10+ because development began when that was the most stable node and we don't want to unnecessarily break people.

If we drop support, it requires a major bump of all of our libraries and there is a ton of work to do before we are able to do that.  We will be upgrading yargs when that time comes.
