### ISSUE TITLE
Outdated and Vulnerable Dependency

### ISSUE THREAD

**Issue by chillheart** [gulpjs/gulp-cli#202]
gulp-cli uses yargs@^7.1.0 that has a child dependency (yarg-parser) that contains a known vulnerability. The vulnerability has been patched and yargs@>13.0.0.0 uses the updated dependency.

The reproduction steps are available on the vulnerability disclosure.

https://snyk.io/vuln/SNYK-JS-YARGSPARSER-560381

**Comment by phated** [comment]
That doesn't effect build tools unless you are passing user input to an exec on your server. If you are doing that, you have MUCH bigger problems than this.

Also, yargs 13 breaks our compatibility matrix. I'd highly suggest not using snyk, they do a poor job of representing the real world of open source development.

**Comment by aarongoldenthal** [comment]
I won't disagree about the actual susceptibility of this vulnerability, but it is frustrating to have to maintain exception lists for deprecated software with potential vulnerabilities so automated scans are not failing with false positives.  This vulnerability is fixed in every supported `yargs` release (originally more than a year ago).

I do appreciate the compatibility matrix problem as well, but it seems unlikely that maintaining `"node": ">= 0.10"` is going to be achievable forever.

**Comment by phated** [comment]
@aarongoldenthal It's as frustrating to receive your comment as it is for you to maintain some list. Stop using garbage automated scanners.
