### ISSUE TITLE
Should index.js be executable?

### ISSUE THREAD

**Issue by erikkemperman** [gulpjs/gulp-cli#80]
Building a tool with separate core and cli, I was looking at gulp and gulp-cli (4.0 branches) for an example. I noticed that `gulp-cli/index.js` has a shebang line and executable mode, but I can't figure out why...

The script exports a function, running it with `./index.js` doesn't really do anything, it seems to me. Is there something clever going on here, or is this maybe a leftover of an earlier setup? It looks like it would have made sense before these:

https://github.com/gulpjs/gulp/commit/95ce47adc59bc882370e21c48557a766efc62998

https://github.com/gulpjs/gulp-cli/commit/6b2c2ef8827980af5f9c3b0b107173aa70c484ca

I was also wondering why gulp has its own executable `bin/gulp.js`, which just requires gulp-cli and runs the exported function -- but now I suspect that this is in case users do `npm install -g gulp` (instead of installing only gulp-cli globally as recommended in the getting started guide). Have I got that right?

**Comment by phated** [comment]
The `index.js` file should be like that.  The executable lives in `bin/gulp.js` as described at https://github.com/gulpjs/gulp-cli/blob/master/package.json#L16

You are correct about gulp proper, but also if you do a local install of gulp and use the `gulp` command in your npm-scripts (which I and much of core does instead of a global install), it hoists your local bin files to your path and I didn't want to force people to have gulp & gulp-cli as devDependencies (grunt does this).

**Comment by phated** [comment]
Sorry, mistype in the first sentence. Edited

**Comment by erikkemperman** [comment]
Created a PR for index.js -- sorry about the triple commit refs here, force-pushed twice to restart Travis. There were failing tests due to a change in Undertaker, tacked a fix for that onto the PR.
