### ISSUE TITLE
options shown at CLI --help seem to disappear when you use them

### ISSUE THREAD

**Issue by mbabauer** [gulpjs/gulp-cli#88]
I have been struggling to get gulp to work in WebStorm 2016.1.3 because it's trying to use either a `--no-color` option when it resyncs the task list or a `--color` option when it runs the app.

I have the following versions installed:
node: 5.7.1
gulp: 3.9.1
gulp-cli: 1.2.1

When I run the following:
```bash
./node_modules/gulp-cli/bin/gulp.js --help
```

I get a listing that shows a lot of options, included the two mentioned above:
```bash
$ ./node_modules/gulp-cli/bin/gulp.js --help

Usage: gulp [options] tasks

Options:
  --help, -h       Show this help.                                     [boolean]
  --version, -v    Print the global and local gulp versions.           [boolean]
  --require        Will require a module before running the gulpfile. This is
                   useful for transpilers but also has other applications.
                                                                        [string]
  --gulpfile       Manually set path of gulpfile. Useful if you have multiple
                   gulpfiles. This will set the CWD to the gulpfile directory as
                   well.                                                [string]
  --cwd            Manually set the CWD. The search for the gulpfile, as well as
                   the relativity of all requires will be from here.    [string]
  --verify         Will verify plugins referenced in project's package.json
                   against the plugins blacklist.
  --tasks, -T      Print the task dependency tree for the loaded gulpfile.
                                                                       [boolean]
  --depth          Specify the depth of the task dependency tree.
  --tasks-simple   Print a plaintext list of tasks for the loaded gulpfile.
                                                                       [boolean]
  --tasks-json     Print the task dependency tree, in JSON format, for the
                   loaded gulpfile.
  --color          Will force gulp and gulp plugins to display colors, even when
                   no color support is detected.                       [boolean]
  --no-color       Will force gulp and gulp plugins to not display colors, even
                   when color support is detected.                     [boolean]
  --silent, -S     Suppress all gulp logging.                          [boolean]
  --continue       Continue execution of tasks upon failure.           [boolean]
  --log-level, -L  Set the loglevel. -L for least verbose and -LLLL for most
                   verbose. -LLL is default.                             [count]
```

Notice the options have both listed.  However, when I run:
```bash
./node_modules/gulp-cli/bin/gulp.js --color
```

I get "error: unknown option '--color'".  Same when I try to use `--no-color`.

**Comment by mbabauer** [comment]
Anyone know what is going on here?  I tried nuking all the packages under node_modules and re-installing via `npm`, but it didn't change anything.

**Comment by phated** [comment]
Unable to duplicate this.  It is not advisable to install gulp-cli locally alongside an old version of gulp.  It is made to be installed globally (and included as a dependency of gulp 4).  This is either a problem caused by that or something webstorm is doing.

**Comment by monkunashi** [comment]
i have the same problem and am not using webstorm. i have 3.9.1 installed locally and globally and gulp-cli 1.4.0 installed globally (not locally).  most options do not work. -T, --tasks, --tasks-simple, --tasks-json, --color, --no-color, --continue and probably some others. options that i know DO work, are -v, --verify and --help. all other options just report something along the lines of "error: unknown option '--tasks' "

**Comment by sttk** [comment]
@monkunashi 
>  i have 3.9.1 installed locally and globally and

Isn't it due to gulp installed globally? Uninstall gulp from global and try again.

**Comment by monkunashi** [comment]
@sttk

No, I've tried so many combinations of different versions and installing just locally, just globally and both... No matter what I do, I can't get it to work. I've since given up, But if you have any other ideas or knowledge of version incompatibilities with node or npm or anything wierd like that, I'm open to try again

**Comment by sttk** [comment]
@monkunashi I have no idea about your issue. All I can say is that do check there are no old versions of gulp and gulp-cli which are installed globally, then install them by `npm install -g gulp-cli; npm install gulp`.

If possible, you should use gulp v4, which is the latest version recently released, by `npm install -g gulp-cli; npm install gulp@next`.

If it still does not resolve, search or ask your question on [StackOverflow](https://stackoverflow.com/questions/tagged/gulp), etc.

**Comment by monkunashi** [comment]
Thanks for the tips. Though it didn't help. I've searched everywhere for an answer. The few others with this problem that ask get shrugged off as it being user error. I haven't tried posting to stack overflow about it yet though.

I have one idea, but not sure how to find out if it's right or not... But I don't have admin rights on my computer, so I have the npm prefix option to set my npm global to my users/username/.npm-global. I'm not sure if this could potentially be incompatible with something gulp-cli is expecting...  That's the only thing I can think of since I'm guessing most people have admin and don't need to do this, so it's probably an uncommon configuration.

**Comment by phated** [comment]
@monkunashi How do you expect anyone to help you when you can't produce a reproduction case independent of your system?  Unless you can do that or debug further, no one will be able to help you.

**Comment by monkunashi** [comment]
@phated 

So because I don't have another computer with restricted access, I should refrain from asking questions? Someone else started this post... I was just saying I also have the issue. Then I informed of a potential cause, albeit a guess, I'm not a complete idiot... It makes sense. But sorry if you feel I should just keep my ideas and theories to myself until I decide to by myself an expensive apple computer of my own. 

If it matters, everyone else on my team has the same issue . So there's your reproduction. The only thing I can't reproduce is a working version.

**Comment by phated** [comment]
> If it matters, everyone else on my team has the same issue . So there's your reproduction. The only thing I can't reproduce is a working version.

How does this help us UNPAID maintainers?  It feels like you expect us to ssh into your box and debug your problem.  A reproduction case would be something like a repository that exhibits the problem that a maintainer can actually run on your machine.

Also, you probably **should** refrain from coming into a project and asking for free support when your github profile looks like:
<img width="1087" alt="screen shot 2018-01-28 at 2 42 39 pm" src="https://user-images.githubusercontent.com/992373/35487526-b00ca1c0-0439-11e8-84ea-e08d908b18e7.png">
