### ISSUE TITLE
Set `cwd` before enabling require hooks

### ISSUE THREAD

**Issue by weswigham** [gulpjs/gulp-cli#89]
[Moved from liftoff](https://github.com/js-cli/js-liftoff/issues/78#issuecomment-233461979)

> This way the appropriate cwd can be set when all register hooks get hooked in. This is an issue in, for example, gulp when using ts-node in a subdirectory with --cwd. The cwd passed is not respected by the require hooks included by liftoff since the cwd is only set during launch (so it is not set when the require hook is loaded).

@phated Says the change would alter [these lines](https://github.com/gulpjs/gulp-cli/blob/master/index.js#L131-L137), but I'm under the impression that it would actually be a bit more, since the issue is that the cwd needs to be changed roughly in the middle of `buildEnvironment` (just before register hooks are enabled), rather than after it (as it is now). The other option is to just to set it very early - before `launch` is ever called.

**Comment by phated** [comment]
Digging deeper, it seems that rechoir should already be doing this.  See https://github.com/js-cli/js-rechoir/blob/master/lib/register.js#L6-L7

**Comment by weswigham** [comment]
It's setting `basedir` when resolving the module, but not actually doing `process.chdir` to alter the results of `process.cwd` within the things it requires.

**Comment by weswigham** [comment]
So... ultimately an issue on `rechoir`, then?

**Comment by phated** [comment]
It shouldn't need to change the directory because it is manually resolving the module.  Using the `resolve` module, it changes 'coffee-script' into '/User/phated/project/node_modules/coffee-script/index.js' (or something like that) and then we require that.  If you are having problems, you can insert a `console.log` there to find out what you environment is resolving to.  I think you need to do some more debugging.

**Comment by weswigham** [comment]
No no no, the module is successfully resolved. But the _code within the module expects process.cwd() to be set correctly_.

**Comment by phated** [comment]
They should adopt a pattern like babel instead of us bending to their terrible pattern. Thanks for digging into this.

**Comment by blakeembrey** [comment]
@phated Can you point out the pattern used in Babel to enable this?

**Comment by phated** [comment]
@blakeembrey it looks like babel is broken in a subtle way at lines https://github.com/babel/babel/blob/master/packages/babel-register/src/node.js#L38-L42 - basically they store the `process.cwd()` when loaded but use it later to determine ignores.  They should be looking up `process.cwd()` each time because `process.chdir()` might have been called.

I would recommend doing the `process.cwd()` lookup dynamically and not store it.  I'm guessing it's a lightweight lookup as opposed to the actual filesystem operations and transpilation.

**Comment by blakeembrey** [comment]
@phated That is how it works, but it doesn't work here because gulp changes the directory _after_ the call to register. We need to load the configuration file **on** the call to `register`.

**Comment by phated** [comment]
Why do you have to load the config file when the module is loaded?  It seems like it can be done upon the first/each require.  Babel does it inside their [`compile`](https://github.com/babel/babel/blob/master/packages/babel-register/src/node.js#L52-L57) which is called upon each extension require.  Come to think of it, that is probably what I was talking about in the past (I honestly couldn't remember nor get the context from the threads).

**Comment by blakeembrey** [comment]
@phated That's how it works today, but the config file is required to decide whether to hook onto `.js`. The workaround is to always hook onto `.js` and just ignore it when the config file disagrees, which could work, but isn't ideal as I'm sure more people than just I will eventually run into this. See my comment from https://github.com/gulpjs/gulp-cli/issues/89#issuecomment-263090845.

**Comment by blakeembrey** [comment]
Note, also, that Babel probably compiles `.js` by default. TypeScript, however, does not. This lazy load fails in that case, as `ts-node` hasn't bound itself to `.js` _before_ a `.js` file is required if no `.ts` file has ever been loaded yet.

**Comment by phated** [comment]
@blakeembrey babel registers on `.js` unless you configure it to not (js-liftoff uses this config option) but it also allows you to specify `ignore`s in your config that will defer to the original require and avoid transpilation.  I believe their way is the best way to do this.

**Comment by blakeembrey** [comment]
@phated I'm not sure if you're just missing the point or I am, but what exactly are you suggesting? Everything you've suggested is exactly how `ts-node` is written, but I'm going to be reverting the work soon because it's honestly too much effort and has create other bugs (such as `node --require ts-node/register script.js` can not work, because `ts-node/register` is entirely lazy to support gulp).

**Comment by phated** [comment]
@blakeembrey why won't you hook the initial `.js` file?  Is that a node bug/problem?  I've not looked at the source code for `ts-node/register`, as I was just answering your questions about babel.

**Comment by blakeembrey** [comment]
No, we don't want to compile JavaScript by default. We only compile `.ts` by default. We use the configuration file to decide if we should also compile `.js`. I'm not sure people would be happy if TypeScript suddenly started compiling their `.js` files (especially because it's not a TypeScript default, whereas I contrasted it to Babel where they are expected to compile `.js` so this isn't an issue).

**Comment by blakeembrey** [comment]
I could make a PR to https://github.com/js-cli/js-interpret to support `.js` compilation with TypeScript, but it's entirely possible it'd break some peoples projects who currently expect that not to happen and are using `ts-node` as a dev dependency.

**Comment by phated** [comment]
Ah, I think we've come to the crux of it.  I'm not telling you to __compile__ upon `.js` files, but to instead register a `require.extensions` method __for__ `.js` like babel does (this should be configurable through `register({ extensions: ['.js'] })` like babel also).  You don't actually do the transpilation in the hook but instead you load the config to know whether or not the transpilation is necessary.  If the transpilation is not necessary, you just defer to the original require hook (you can store this in a variable before you overwrite it).  This would only add overhead to the initial require because I'm guessing you will cache the config file upon load.

**Comment by blakeembrey** [comment]
Right, that's what I commented here - https://github.com/gulpjs/gulp-cli/issues/89#issuecomment-263431104. It's not really ideal though, as every `.js` call will go through the loader now (e.g. it'll be in stack traces, potentially causing others issues with `.js` files to be attributed to TypeScript). Yes, it only adds overhead for the initial config file load and a tiny function call overhead to the rest. If it's not something Gulp is planning to fix, it's probably the solution I'll end up using.

However, what is the major issue with reordering so all loaders act as expected?
